In [3]:
import torch
from torch import tensor
import numpy as np

In [2]:
torch.__version__

'2.0.1'

In [3]:
scalar = torch.tensor(7)

In [4]:
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [11]:
vector = tensor([7, 7, 7, 7])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([4])

In [14]:
matrix = tensor([[7,8],
                 [9,10]])

In [15]:
matrix.ndim

2

In [16]:
matrix.shape

torch.Size([2, 2])

In [17]:
tensor = tensor([[[1, 2, 3],
                 [3, 6, 9],
                 [2, 4, 5]]])

In [18]:
tensor.ndim

3

In [19]:
tensor.shape

torch.Size([1, 3, 3])

In [21]:
tensor_1 = torch.tensor([[[1, 2, 3],
                    [3, 4, 5],
                    [6, 7, 8]], 
                   [[3, 3, 3,],         
                    [4, 4, 4],
                    [5, 5, 5]]])

In [25]:
tensor_1

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]],

        [[3, 3, 3],
         [4, 4, 4],
         [5, 5, 5]]])

In [30]:
a = tensor_1[1][0][1]

In [31]:
a.ndim

0

In [51]:
random_tensor = torch.rand(size=(3,3,3,))

In [52]:
random_tensor

tensor([[[0.9735, 0.7058, 0.1879],
         [0.2685, 0.2225, 0.9017],
         [0.6646, 0.7429, 0.7244]],

        [[0.2770, 0.4371, 0.3155],
         [0.3091, 0.3405, 0.7802],
         [0.6604, 0.5338, 0.2254]],

        [[0.4340, 0.9663, 0.5057],
         [0.5478, 0.1033, 0.1062],
         [0.6408, 0.3104, 0.8553]]])

In [53]:
zeros_tensor = torch.zeros(size = (2 ,3, 4))

In [54]:
zeros_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [55]:
ones_tensor = torch.ones(size =(1, 2 ,2))

In [56]:
ones_tensor

tensor([[[1., 1.],
         [1., 1.]]])

In [57]:
my_arange = torch.arange(1, 10, 2)

In [60]:
my_arange

tensor([1, 3, 5, 7, 9])

In [61]:
my_arange_ones = torch.ones_like(input=my_arange)

In [62]:
my_arange_ones

tensor([1, 1, 1, 1, 1])

In [63]:
my_arange_ones.dtype

torch.int64

In [64]:
zeros_tensor.dtype

torch.float32

In [69]:
a = 0.548980349309430493049330940349034904950459045940594

In [76]:
torch.tensor(a, dtype = torch.float64)

tensor(0.5490, dtype=torch.float64)

In [78]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16)

In [79]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [80]:
tensor.device

device(type='cpu')

In [82]:
## Tensor operations

In [87]:
exp_tensor_1 = torch.tensor([1,2,3])

In [86]:
exp_tensor.mul(10)

tensor([10, 20, 30])

In [85]:
exp_tensor

tensor([1, 2, 3])

In [88]:
exp_tensor_2 = torch.tensor([1,2,3])

In [89]:
usual_mul_tensor = exp_tensor_1 * exp_tensor_2

In [90]:
mul_tensor

tensor([1, 4, 9])

In [91]:
torch.matmul(exp_tensor_2, exp_tensor_2)

tensor(14)

In [93]:
t_1 = torch.tensor([[1, 2],
                   [3, 4], 
                   [5, 6]])

t_2_right = torch.tensor([[1, 2, 3],
                         [4, 5, 6]])

t_2_wrong= torch.tensor([[1, 4],
                        [2, 5],
                        [3, 6]])

In [94]:
right_mul = torch.matmul(t_1, t_2_right)

In [95]:
right_mul

tensor([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])

In [102]:
wrong_mul = torch.matmul(t_1, t_2_wrong)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [99]:
t_11 = torch.tensor([[1, 2, 3]])

t_22_right = torch.tensor([[4],
                            [5],
                            [6]])

t_22_wrong= torch.tensor([[4,5,6]])

In [100]:
right_mul_1 = torch.matmul(t_11, t_22_right)

In [101]:
right_mul_1

tensor([[32]])

In [103]:
wrong_mul = torch.matmul(t_11, t_22_wrong)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x3 and 1x3)

In [108]:
t_22_right.T

tensor([[4, 5, 6]])

In [131]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
torch.manual_seed(42)
linear = torch.nn.Linear(in_features = 2, out_features = 6)
output = linear(tensor_A)

In [129]:
output

tensor([[0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
        [1.7186, 1.4009, 3.5818, 1.7408, 2.6017, 2.5123]],
       grad_fn=<AddmmBackward0>)

## Finding the min, max, mean, sum, etc (aggregation)

In [133]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [135]:
torch.mean(x.type(torch.float32)), torch.max(x), torch.min(x), torch.sum(x)

(tensor(45.), tensor(90), tensor(0), tensor(450))

In [136]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [137]:
x.type(torch.float32)

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [146]:
torch.argmax(x), torch.argmin(x)

(tensor(9), tensor(0))

In [147]:
tensor_A

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [148]:
random_tensor

tensor([[[0.9735, 0.7058, 0.1879],
         [0.2685, 0.2225, 0.9017],
         [0.6646, 0.7429, 0.7244]],

        [[0.2770, 0.4371, 0.3155],
         [0.3091, 0.3405, 0.7802],
         [0.6604, 0.5338, 0.2254]],

        [[0.4340, 0.9663, 0.5057],
         [0.5478, 0.1033, 0.1062],
         [0.6408, 0.3104, 0.8553]]])

In [182]:
tensor_A

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [191]:
rand_a = torch.rand(size = (3, 2, 3))
rand_a

tensor([[[0.5779, 0.9040, 0.5547],
         [0.3423, 0.6343, 0.3644]],

        [[0.7104, 0.9464, 0.7890],
         [0.2814, 0.7886, 0.5895]],

        [[0.7539, 0.1952, 0.0050],
         [0.3068, 0.1165, 0.9103]]])

In [192]:
torch.reshape(rand_a, (3, 3, 2))

tensor([[[0.5779, 0.9040],
         [0.5547, 0.3423],
         [0.6343, 0.3644]],

        [[0.7104, 0.9464],
         [0.7890, 0.2814],
         [0.7886, 0.5895]],

        [[0.7539, 0.1952],
         [0.0050, 0.3068],
         [0.1165, 0.9103]]])

In [195]:
rand_a.view((3, 3, 2))

tensor([[[0.5779, 0.9040],
         [0.5547, 0.3423],
         [0.6343, 0.3644]],

        [[0.7104, 0.9464],
         [0.7890, 0.2814],
         [0.7886, 0.5895]],

        [[0.7539, 0.1952],
         [0.0050, 0.3068],
         [0.1165, 0.9103]]])

In [203]:
tensor_AA = torch.rand(size = (2, 2))
tensor_BB = torch.rand(size = (2, 2))
tensor_AA

tensor([[0.0041, 0.1088],
        [0.1637, 0.7025]])

In [204]:
tensor_BB

tensor([[0.6790, 0.9155],
        [0.2418, 0.1591]])

In [207]:
stack = torch.stack((tensor_AA, tensor_BB))
stack

tensor([[[0.0041, 0.1088],
         [0.1637, 0.7025]],

        [[0.6790, 0.9155],
         [0.2418, 0.1591]]])

In [214]:
a = torch.squeeze(tensor_BB, dim=1)

In [216]:
exp_tensor = torch.rand(size = (3, 1, 3, 1, 2))

In [223]:
exp_tensor

tensor([[[[[0.7653, 0.2979]],

          [[0.8035, 0.3813]],

          [[0.7860, 0.1115]]]],



        [[[[0.2477, 0.6524]],

          [[0.6057, 0.3725]],

          [[0.7980, 0.8399]]]],



        [[[[0.1374, 0.2331]],

          [[0.9578, 0.3313]],

          [[0.3227, 0.0162]]]]])

In [220]:
sqz_t = torch.squeeze(exp_tensor)

In [227]:
x = torch.arange(1. , 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [228]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [233]:
a = torch.arange(8).view(4,2)

In [234]:
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

In [273]:
z = torch.zeros(3, 2)
z

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [274]:
x = z.view(2, 3)

In [275]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [276]:
z

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [277]:
z.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [278]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [279]:
x.fill_(2)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [280]:
z

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [282]:
x = torch.tensor([5., 2., 3., 4., 5., 6., 7.])

In [293]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [298]:
x_original = torch.rand(size=(224, 223, 3))

In [299]:
x_permuted = x_original.permute(2, 1, 0) 

In [300]:
x_permuted.shape

torch.Size([3, 223, 224])

## Indexing (selecting data from tensors)¶

In [301]:
x = torch.arange(1, 10).reshape(1, 3, 3)

In [302]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [306]:
x[0][0]

tensor([1, 2, 3])

In [309]:
x[:, 1]

tensor([[4, 5, 6]])

In [316]:
new_x_rand = (torch.rand(2, 3, 3,) * 100).type(torch.int8)

In [327]:
new_x_rand, new_x_rand.shape

(tensor([[[74, 21,  3],
          [ 7,  3, 44],
          [44, 18, 30]],
 
         [[61, 23, 13],
          [24, 21,  9],
          [26, 52,  9]]], dtype=torch.int8),
 torch.Size([2, 3, 3]))

In [334]:
new_x_rand[:,1]

tensor([[ 7,  3, 44],
        [24, 21,  9]], dtype=torch.int8)

## PyTorch tensors & NumPy

In [340]:
np_array = np.arange(1.0, 8.0)
my_tensor = torch.from_numpy(np_array)

In [343]:
np_array, my_tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

## Running tensors on GPUs (and making faster computations)

In [2]:
!nvidia-smi

Thu Oct 12 13:48:23 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:07:00.0 Off |                  N/A |
|  0%   34C    P8    17W / 175W |     26MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [5]:
torch.cuda.is_available()

True

In [9]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [11]:
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU

In [13]:
tensor = torch.tensor([1, 2 , 3])

In [14]:
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [15]:
id(tensor)

140168040246784

In [21]:
tensor_on_gpu = tensor.to(device)

In [23]:
id(tensor_on_gpu), tensor_on_gpu.device

(140168042634672, device(type='cuda', index=0))

In [24]:
tensor_on_cpu = tensor_on_gpu.cpu()

In [29]:
id(tensor_on_cpu)

140168027369856