# 00. PyTorch Fundamentals Exercises

### 1. Create a random tensor with shape (7, 7).

In [3]:
import torch

tensor([[0.1100, 0.2121, 0.9704, 0.8369, 0.2820, 0.3742, 0.0237],
        [0.4910, 0.1235, 0.1143, 0.4725, 0.5751, 0.2952, 0.7967],
        [0.1957, 0.9537, 0.8426, 0.0784, 0.3756, 0.5226, 0.5730],
        [0.6186, 0.6962, 0.5300, 0.2560, 0.7366, 0.0204, 0.2036],
        [0.3748, 0.2564, 0.3251, 0.0902, 0.3936, 0.6069, 0.1743],
        [0.4743, 0.8579, 0.4486, 0.5139, 0.4569, 0.6012, 0.8179],
        [0.9736, 0.8175, 0.9747, 0.4638, 0.0508, 0.2630, 0.8405]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [ ]:
# (7,7) (7, 1)

In [7]:
random_tensor_1 = torch.rand(size = (7, 7))
random_tensor_2 = torch.rand(size = (1, 7))
mul_tensor = random_tensor_1.matmul(random_tensor_2.T)

In [8]:
mul_tensor

tensor([[1.1563],
        [2.4691],
        [1.7151],
        [0.7227],
        [1.7563],
        [1.9914],
        [1.9536]])

###  4. Set the random seed to 0 and do 2 & 3 over again.

In [19]:
torch.manual_seed(0)
random_tensor_with_seed = torch.rand(size = (7,7))
print(random_tensor_with_seed)

random_tensor_11 = torch.rand(size = (7, 7))
random_tensor_22 = torch.rand(size = (1, 7))
mul_tensor = random_tensor_1.matmul(random_tensor_2.T)
print(mul_tensor)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[1.1563],
        [2.4691],
        [1.7151],
        [0.7227],
        [1.7563],
        [1.9914],
        [1.9536]])


## create seed for GPU and mult them

In [79]:
torch.manual_seed(1234)
device = 'cuda'

gpu_tensor_1 = torch.rand(size = (2,3)).to(device)
gpu_tensor_2 = torch.rand(size = (2,3)).to(device)


In [80]:
mult_gpu_tensor = gpu_tensor_1.matmul(gpu_tensor_2.T)

In [82]:
mult_gpu_tensor

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [83]:
max = torch.max(mult_gpu_tensor)
max
arg_max = torch.argmax(mult_gpu_tensor)
arg_max

tensor(3, device='cuda:0')

In [84]:
min = torch.min(mult_gpu_tensor)
min
arg_min = torch.argmin(mult_gpu_tensor)
arg_min

tensor(0, device='cuda:0')

### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [99]:
torch.manual_seed(7)
random_tensor_final = torch.rand(size = (1, 1, 1, 10))
random_tensor_final_sqz = torch.squeeze(random_tensor_final)
random_tensor_final, random_tensor_final.size(), random_tensor_final_sqz, random_tensor_final_sqz.size()

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))